In [1]:
import importlib.util

# load modules - POC model
def load_module(model_path):
    '''loads module containing models given path'''
    spec = importlib.util.spec_from_file_location('module',model_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

fname_module1 = 'Model_C3F2all.py'
module = load_module(fname_module1)

In [2]:
# load modules - POC model
def load_module(model_path):
    '''loads module containing models given path'''
    spec = importlib.util.spec_from_file_location('module',model_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

In [3]:
fname_module1 = 'Model_C3F2all.py'

In [4]:
module = load_module(fname_module1)

ModuleNotFoundError: No module named 'tensorflow'

In [6]:
import pandas as pd

In [5]:
folder = '../data/'
fname_p1 = folder+'scerevisiae_good_rsd1_lmbda22_Model_C3F2all_1234_c008090fd8e4b9971fe71eed502c9f7b_best.p'

In [7]:
p = pd.read_csv(fname_p1,sep=';')

In [8]:
p

path  epoch    beta_1  \
1  ../2019_3_46/_run_hyperas_scerevisiae_all/resu...    114  0.608113   

     beta_2  coef_det_k  dense5  dense6  dilation1  dilation2  dilation3  ...  \
1  0.900722    0.841135     128      32          1          1          4  ...   

   stride3  test_loss  test_val_det_k  val_coef_det_k  val_loss  \
1        1   1.613878        0.822046         0.86998  1.591834   

                                            filename  diff_perc  region  iter  \
1  2019_3_46|scerevisiae_good_rsd1_lmbda22_Model_...  -0.055098    2/sc  1375   

   overfit  
1  (0,0.1]  

[1 rows x 44 columns]

In [9]:
p = p.iloc[0]
p.drop(['path','overfit'],inplace=True)
print(p.shape)

(42,)


/home/rosalindpan/.local/lib/python3.7/site-packages/pandas/core/generic.py:4150: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(obj)


In [5]:
# load p
p = pd.read_csv(fname_p1,sep=';')
p = p.iloc[0]
p.drop(['path','overfit'],inplace=True)
print(p.shape)

# load data
X_train, X_test, Y_train, Y_test = module.load_data(fname_data1) 
# Y = np.concatenate((Y_train, Y_test))
# X = np.concatenate((X_train[0], X_test[0]))
print(len(X_test))
print(len(Y_test))

# model
input_shapes = [sl.shape[1:] for sl in X_train]
model = module.POC_model(input_shapes, p)
# set weights model 1
print("Loading model 1 from disk..")
model.load_weights(fname_weights1)

NameError: name 'k' is not defined

In [11]:
from numpy import load

data = load('../data/scerevisiae.rsd1.lmbda_22.1000.npz')

In [12]:
lst = data.files
for item in lst:
    print(item)
    print(data[item])

arr_0
[[[1 0 0 0]
  [1 0 0 0]
  [0 0 1 0]
  ...
  [1 0 0 0]
  [0 0 1 0]
  [0 0 0 1]]

 [[0 0 0 1]
  [0 0 1 0]
  [1 0 0 0]
  ...
  [0 0 1 0]
  [0 0 1 0]
  [1 0 0 0]]

 [[0 0 0 1]
  [1 0 0 0]
  [0 1 0 0]
  ...
  [0 0 1 0]
  [0 0 1 0]
  [0 0 0 1]]

 ...

 [[1 0 0 0]
  [0 0 1 0]
  [0 0 0 1]
  ...
  [0 1 0 0]
  [1 0 0 0]
  [1 0 0 0]]

 [[0 1 0 0]
  [0 0 1 0]
  [1 0 0 0]
  ...
  [0 0 0 1]
  [0 1 0 0]
  [0 1 0 0]]

 [[0 0 1 0]
  [0 1 0 0]
  [0 1 0 0]
  ...
  [0 1 0 0]
  [1 0 0 0]
  [0 0 0 1]]]
arr_1
[[[1 0 0 0]
  [0 0 0 1]
  [0 0 1 0]
  ...
  [1 0 0 0]
  [0 0 1 0]
  [0 0 0 1]]

 [[0 0 0 1]
  [1 0 0 0]
  [0 1 0 0]
  ...
  [0 0 0 1]
  [0 0 0 1]
  [1 0 0 0]]

 [[0 0 0 1]
  [0 0 0 1]
  [0 0 1 0]
  ...
  [1 0 0 0]
  [0 0 1 0]
  [0 0 0 1]]

 ...

 [[0 0 0 1]
  [1 0 0 0]
  [1 0 0 0]
  ...
  [0 0 0 1]
  [0 0 1 0]
  [0 0 0 1]]

 [[1 0 0 0]
  [1 0 0 0]
  [0 0 1 0]
  ...
  [0 0 0 1]
  [0 1 0 0]
  [0 1 0 0]]

 [[0 0 0 1]
  [0 0 1 0]
  [0 0 1 0]
  ...
  [0 0 0 1]
  [0 1 0 0]
  [1 0 0 0]]]
arr_2
[[  51 344